packages:
  - name: test-yaml-alias
    shared: true
    actions:
      - &default_action
        annotations:
          provide-api-key: true
        runtime: nodejs:default
        name: gateway
        limits:
          timeout: 3000
      - <<: *default_action
        name: gateway
      - <<: *default_action
        name: cli-gateway
        webSecure: xyzzy
