#!/bin/bash

VERSION=$(jq -r .version < package.json)

cat << EOT > src/version.ts
////////////////////////////////////////////////////////////////
// THIS FILE WAS AUTO-GENERATED BY scripts/generateVersion.sh
// DO NOT EDIT MANUALLY
////////////////////////////////////////////////////////////////

export const version = '$VERSION';
EOT