name: Build Functions Deployer

on:
  workflow_call:

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        node-version: [16.x]
    runs-on: ${{ matrix.os }}
    concurrency: functions_deployer_build_${{ matrix.os }}_${{ matrix.node-version }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Check build process
      run: npm run build
