name: Unit Tests

on:
  workflow_call:

jobs:
  unit-test:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node-version: [16.x]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests with coverage
        run: npm run test:coverage --coverage
