name: Unit Tests

on:
  workflow_call:

jobs:
  unit-test:
    strategy:
      matrix:
        node-version: ['16.x', '18.x']
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests with coverage
        run: npm run test:coverage --coverage
