name: Pull Request

on: [push, pull_request]

jobs:
  build:
    uses: ./.github/workflows/_build.yml
  lint:
    uses: ./.github/workflows/_lint.yml
  # unit-tests:
  #   uses: digitalocean/ui-actions/.github/workflows/unit-tests.yml@main
  # types:
  #   uses: digitalocean/ui-actions/.github/workflows/types.yml@main
  # prettier:
  #   uses: digitalocean/ui-actions/.github/workflows/prettier.yml@main