name: Pull Request

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/_build.yml
  lint:
    uses: ./.github/workflows/_lint.yml
  unit-tests:
    uses: ./.github/workflows/_unit-test.yml
  e2e-tests:
    uses: ./.github/workflows/_e2e-tests.yml
    secrets:
      DO_API_KEY: ${{ secrets.DO_API_KEY }}
      TEST_NAMESPACE: ${{ secrets.TEST_NAMESPACE }}